# Basic
title: Xiaoteng Zhou
subtitle: Master Candidate at Tsinghua University
welcome_message: <a href="https://scholar.google.com/citations?user=4dVGSi4AAAAJ&hl=zh-CN&oi=ao" target="_blank">My Geogle Scholar Profile</a>
description: Personal Website.
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Researchgate, description: My Researchgate, url: 'https://www.researchgate.net/profile/Xiaoteng_Zhou2'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: onevcat
    github: longteng94
    twitter: longteng944
    gplus: u/0/
    mail: longteng944@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
